---
- name: Install required packages on Fedora
  dnf:
    name: "{{ required_packages }}"
    state: latest
  vars:
    required_packages:
      - btrfs-progs-devel
      - device-mapper-devel
      - git
      - glib2-devel
      - glibc-devel
      - glibc-static
      - golang
      - gpgme-devel
      - libassuan-devel
      - libgpg-error-devel
      - libseccomp-devel
      - libselinux-devel
      - ostree-devel
      - pkgconfig
      - runc
  when: ansible_distribution == 'Fedora'
  become: yes

- name: Clone cri-o repository
  git:
    repo: "{{ crio_git_repo }}"
    refspec: "{{ crio_git_refspec }}"
    dest: "{{ crio_git_dest }}"
    accept_hostkey: "{{ crio_git_accept_hostkey }}"

- name: Make cri-o install tools
  make:
    target: install.tools
    chdir: "{{ crio_git_dest }}"

- name: Make cri-o
  make:
    chdir: "{{ crio_git_dest }}"

- name: Install cri-o
  make:
    target: install
    chdir: "{{ crio_git_dest }}"
  become: yes

- name: Install cri-o configuration
  make:
    target: install.config
    chdir: "{{ crio_git_dest }}"
  become: yes

- name: Add systemd service configuration
  copy:
    src: systemd/crio.service
    dest: /etc/systemd/system/crio.service
  become: yes
  register: crio_service_configuration

- name: Reload systemd unit configurations
  command: systemctl daemon-reload
  become: yes
  when: crio_service_configuration | changed

- name: Configure the cri-o service
  service:
    name: crio
    enabled: yes
    state: started
  become: yes
...
